export const themes = {
  nhl: {
    name: 'NHL',
    '--bg-body': '#000',
    '--bg-app': '#000',
    '--bg-header': '#000',
    '--bg-content': '#fff',
    '--bg-card': '#fff',
    '--bg-card-hover': '#f5f5f5',
    '--bg-input': '#fff',
    '--bg-highlight': '#e8f4fd',
    '--bg-row-even': '#fafafa',
    '--bg-row-hover': '#f0f8ff',
    '--bg-empty': '#fff',
    '--text-primary': '#333',
    '--text-secondary': '#999',
    '--text-heading': '#000',
    '--text-header': '#fff',
    '--text-nav': '#aaa',
    '--text-nav-active': '#fff',
    '--text-link': '#000',
    '--border-color': '#ddd',
    '--border-light': '#eee',
    '--border-header': '#333',
    '--btn-bg': '#000',
    '--btn-text': '#fff',
    '--btn-hover': '#333',
    '--btn-danger-bg': '#d32f2f',
    '--btn-danger-hover': '#b71c1c',
    '--error-color': '#d32f2f',
    '--success-color': '#2e7d32',
    '--font-family': "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    '--font-mono': "'Courier New', monospace",
    '--nav-active-border': '#fff',
  },
  heatedRivalry: {
    name: 'Heated Rivalry',
    '--bg-body': '#1a0a0a',
    '--bg-app': '#1a0a0a',
    '--bg-header': '#2a0a1a',
    '--bg-content': '#1e0e12',
    '--bg-card': '#2a1018',
    '--bg-card-hover': '#3a1525',
    '--bg-input': '#1a0a0a',
    '--bg-highlight': '#3a1a2a',
    '--bg-row-even': '#220c14',
    '--bg-row-hover': '#3a1525',
    '--bg-empty': '#1e0e12',
    '--text-primary': '#f0d0a0',
    '--text-secondary': '#b08060',
    '--text-heading': '#ffd700',
    '--text-header': '#ffd700',
    '--text-nav': '#c08060',
    '--text-nav-active': '#ffd700',
    '--text-link': '#ffd700',
    '--border-color': '#5a2030',
    '--border-light': '#3a1525',
    '--border-header': '#8b0030',
    '--btn-bg': '#8b0030',
    '--btn-text': '#ffd700',
    '--btn-hover': '#aa1040',
    '--btn-danger-bg': '#cc0044',
    '--btn-danger-hover': '#ee0055',
    '--error-color': '#ff4466',
    '--success-color': '#ffd700',
    '--font-family': "'Oswald', 'Impact', 'Arial Narrow', sans-serif",
    '--font-mono': "'Courier New', monospace",
    '--nav-active-border': '#ffd700',
  },
  matrix: {
    name: 'Matrix',
    '--bg-body': '#000',
    '--bg-app': '#000',
    '--bg-header': '#000',
    '--bg-content': '#0a0a0a',
    '--bg-card': '#0d1a0d',
    '--bg-card-hover': '#112211',
    '--bg-input': '#0a0a0a',
    '--bg-highlight': '#0d2a0d',
    '--bg-row-even': '#080f08',
    '--bg-row-hover': '#0d2a0d',
    '--bg-empty': '#0a0a0a',
    '--text-primary': '#00ff41',
    '--text-secondary': '#008f11',
    '--text-heading': '#00ff41',
    '--text-header': '#00ff41',
    '--text-nav': '#008f11',
    '--text-nav-active': '#00ff41',
    '--text-link': '#00ff41',
    '--border-color': '#003b00',
    '--border-light': '#002200',
    '--border-header': '#003b00',
    '--btn-bg': '#003b00',
    '--btn-text': '#00ff41',
    '--btn-hover': '#005500',
    '--btn-danger-bg': '#550000',
    '--btn-danger-hover': '#880000',
    '--error-color': '#ff3333',
    '--success-color': '#00ff41',
    '--font-family': "'Courier New', 'Lucida Console', monospace",
    '--font-mono': "'Courier New', monospace",
    '--nav-active-border': '#00ff41',
  }
}

export function applyTheme(themeKey) {
  const theme = themes[themeKey]
  if (!theme) return
  const root = document.documentElement
  for (const [prop, value] of Object.entries(theme)) {
    if (prop.startsWith('--')) {
      root.style.setProperty(prop, value)
    }
  }
  localStorage.setItem('selectedTheme', themeKey)
}

export function getStoredTheme() {
  return localStorage.getItem('selectedTheme') || 'nhl'
}
